function [ handles, croppedImages ] = createNewFolders( handles, croppedImages, folder, k )
    % For every face captured by camera, add the cropped image of the face and its original image
    % to the croppedImages cell array and the referenceImages cell array generated by folder
    % and save the images into folder 'ReferencesImages'
    
    k = size(croppedImages, 2);
    
    for i = 1:handles.cameraFacesNumber-1
        croppedImages{k+i} = handles.cameraSubspaces{i};
        handles.referenceImages{k+i} = handles.cameraReferenceImages{i};
        handles.faceNames{k+i} = handles.cameraFaceNames{i};
        folder = strcat(folder, ...
                handles.cameraFaceNames{i});
        mkdir(folder);
        for j = 1:size(handles.referenceImages{k+i}, 4)                   
            imwrite(uint8(handles.referenceImages{k+i}(:,:,:,j)), strcat(folder, '\', num2str(j), '.jpg'), 'jpg'); 
        end
    end

end

